"""init products reviews

Revision ID: fe429ccc5ab8
Revises: 
Create Date: 2026-05-15 07:24:23.047870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fe429ccc5ab8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='product_schema'
    )
    op.create_index(op.f('ix_product_schema_products_category'), 'products', ['category'], unique=False, schema='product_schema')
    op.create_index(op.f('ix_product_schema_products_name'), 'products', ['name'], unique=False, schema='product_schema')
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product_schema.products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='product_schema'
    )
    op.create_index(op.f('ix_product_schema_reviews_product_id'), 'reviews', ['product_id'], unique=False, schema='product_schema')
    op.create_index(op.f('ix_product_schema_reviews_user_id'), 'reviews', ['user_id'], unique=False, schema='product_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_schema_reviews_user_id'), table_name='reviews', schema='product_schema')
    op.drop_index(op.f('ix_product_schema_reviews_product_id'), table_name='reviews', schema='product_schema')
    op.drop_table('reviews', schema='product_schema')
    op.drop_index(op.f('ix_product_schema_products_name'), table_name='products', schema='product_schema')
    op.drop_index(op.f('ix_product_schema_products_category'), table_name='products', schema='product_schema')
    op.drop_table('products', schema='product_schema')
    # ### end Alembic commands ###
