"""init cart orders

Revision ID: 36a07050e5c7
Revises: 
Create Date: 2026-05-15 07:24:26.703972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '36a07050e5c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='order_schema'
    )
    op.create_index(op.f('ix_order_schema_cart_items_user_id'), 'cart_items', ['user_id'], unique=False, schema='order_schema')
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='order_schema'
    )
    op.create_index(op.f('ix_order_schema_orders_status'), 'orders', ['status'], unique=False, schema='order_schema')
    op.create_index(op.f('ix_order_schema_orders_user_id'), 'orders', ['user_id'], unique=False, schema='order_schema')
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order_schema.orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='order_schema'
    )
    op.create_index(op.f('ix_order_schema_order_items_order_id'), 'order_items', ['order_id'], unique=False, schema='order_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_schema_order_items_order_id'), table_name='order_items', schema='order_schema')
    op.drop_table('order_items', schema='order_schema')
    op.drop_index(op.f('ix_order_schema_orders_user_id'), table_name='orders', schema='order_schema')
    op.drop_index(op.f('ix_order_schema_orders_status'), table_name='orders', schema='order_schema')
    op.drop_table('orders', schema='order_schema')
    op.drop_index(op.f('ix_order_schema_cart_items_user_id'), table_name='cart_items', schema='order_schema')
    op.drop_table('cart_items', schema='order_schema')
    # ### end Alembic commands ###
